#!/bin/bash
#!/bin/sh


BASE="../task2-bash/tmp/guessnum/"

if [ ! -e $BASE ];
   then
   mkdir -p $BASE
fi


FNAME="guessnum.cpp"
FILE="../task1-simple-program/${FNAME}"


if [[ -e $FILE ]];
    then
    EX=$(BASE+=$FNAME)
    if [[ -e $EX ]];
        then
        rm $EX
    fi
    cp $FILE $BASE
fi


TAR="guessnum.tar.gz"
#LINES=$(find -name $TAR | wc -l)
if [ -e $TAR ];
    then
    rm $TAR
fi

tar cfz $TAR $BASE
