#!/bin/bash
#!/bin/sh

#presets
C="g++"
FILE="./tmp/guessnum/guessnum.cpp"
COPY="./copy"

#to copy file if not exists
if [[ ! -e FILE ]];
    then
    ${COPY}
fi

#wins counter
WINS=0

#run and increment WINS if win
function run(){
    $1
    if [ $? -eq 0 ];
        then
        let WINS+=1
        echo "Good job!"
    elif [ $? -eq 1 ];
        then
        echo "Better luck next time."
    fi
}

#compile guessnum.cpp, OUT contains code of g++ compiling error if occurs
OUT=$(${C} ${FILE} 2>&1)
A="./a.out"

#run function run() with parametr A
run $A

#message depends on win/lose
if [[ $WINS -ne 0 ]];
    then
    echo "You win $WINS times!"
else
    echo "You didn't win even once, yikes..."
fi

#delete .out file
rm a.out
